version: '3.4'

services:
  db:
    # For more details on configuring the Postgres Docker image, see:
    #   https://hub.docker.com/_/postgres/
    restart: always
    container_name: decide_db
    image: postgres:10.3-alpine

    # Expose the default Postgres port on localhost
    ports:
      - '5432:5432'
    networks: 
      - decide
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'decide'

    # Copy files from dbinit into the image so that they will be run on boot
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  web:
    restart: always
    container_name: decide_web
    image: decide_web:latest
    build: .
    command: ash -c "python ./decide/manage.py migrate && python ./decide/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app/decide
    depends_on:
      - db
    networks:
      - decide

networks:
  decide:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16
